### ISSUE TITLE
KeyError: 'streams'

### ISSUE THREAD

**Issue by judhat2** [magmastonealex/ffproc#5]
I am getting this error when I run the script.  It still converts the file, but I thought I would still report it.
```python
Traceback (most recent call last):
  File "/ffproc/ffproc.py", line 29, in <module>
    out=json.loads(subprocess.Popen(["ffprobe","-v", "quiet", "-print_format", "json", "-show_format", "-show_streams",fil], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0])["streams"]
KeyError: 'streams'
```

**Comment by magmastonealex** [comment]
That's very strange. What happens if you just run ffprobe on the file? It sounds like it isn't a media file or there's another error.

**Comment by judhat2** [comment]
Ah, my mistake.  I forgot I had moved that file after I started running the script.
